spring:
  application:
    name: user-center
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yupi
    username: root
    password: 123456
server:
  port: 18090

mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: is_delete #全局逻辑删除实体字段
      logic-delete-value: 1 #逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值

